#!/bin/sh

BAT=$(ls /sys/class/power_supply | grep BAT | head -n 1)

battery() {
    cat /sys/class/power_supply/${BAT}/capacity
}

isBatteryCharging() {
    cat /sys/class/power_supply/${BAT}/status
}

batteryIcon() {
    batteryLevel=$(battery)
    isCharging=$(isBatteryCharging)

    if [ "$isCharging" = "Charging" ]; then
        echo "󰄌"  # Charging
        return
    fi

if [ "$batteryLevel" -gt 85 ]; then
    echo ""  # Full battery icon
    exit 0
elif [ "$batteryLevel" -gt 75 ]; then
    echo ""  # 3/4 battery icon
    exit 0
elif [ "$batteryLevel" -gt 50 ]; then
    echo ""  # 1/2 battery icon
    exit 0
elif [ "$batteryLevel" -gt 10 ]; then
    echo ""  # Low battery icon
    exit 0
else
    echo "󰂑"  # Empty battery icon
    exit 0
fi

}


"$@"