#!/bin/sh

networkIcon() {
	active_connection=$(nmcli -t -f ACTIVE,SSID dev wifi | grep '^yes' | cut -d: -f2)

	if [ -z "$active_connection" ]; then
			echo "󱘖"
			exit 1
	fi

	signal_strength=$(nmcli -f IN-USE,SIGNAL dev wifi | grep '*' | awk '{print $2}')

	if [ "$signal_strength" -gt 85 ]; then
    echo "󰤨"
	elif [ "$signal_strength" -gt 75 ]; then
		echo "󰤥"
	elif [ "$signal_strength" -gt 50 ]; then
		echo "󰤢"
	elif [ "$signal_strength" -gt 10 ]; then
		echo "󰤟"
	else
		echo "󰖪"
	fi
}

networkName() {
  nmcli -t -f NAME c show --active | head -n 1
}

"$@"