#!/bin/sh

#
# Adjust the names of the sensors - they are probably different for you
#
# Run:
# sudo sensors-detect
#

GPU_SENSOR="amdgpu-pci-0d00"

CPU_SENSOR="k10temp-pci-00c3"

memory_percent_used() {
	free | grep Mem | awk '{print int(($3/$2 * 100.0) + 0.5)}'
}

storage_percent_used() {
	df --output=pcent . | tail -n 1 | tr -d '[:space:]|%'
}

cpu_temp() {
	sensors "$CPU_SENSOR" | grep 'Tctl:' | awk '{print $2}' | cut -c2-
}

gpu_temp() {
	sensors "$GPU_SENSOR" | grep 'mem:' | awk '{print $2}' | cut -c2-
}

gpu_psu_draw() {
	sensors "$GPU_SENSOR" | grep 'PPT:' | awk '{print $2}'
}

"$@"